server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Rotas para o condominio-service
        - id: condominio-service
          uri: lb://condominio-service
          predicates:
            - Path=/api/condominio/**
          filters:
            - StripPrefix=1

        # Rotas para o iam-service
        - id: iam-service
          uri: lb://iam-service
          predicates:
            - Path=/api/iam/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
