name: Condo+ CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - development

jobs:
  condominio-service:
    name: Test Condominio Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests (condominio_service)
        run: mvn test -pl condominio_service

  eureka-server:
    name: Test Eureka Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests (eureka-server)
        run: mvn test -pl infra/eureka-server

  api-gateway:
    name: Test API Gateway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests (api-gateway)
        run: mvn test -pl infra/api-gateway

