name: Condo+ CI — TP1

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    name: Build & Test (condominio-service)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build & Run Test Suite (condominio-service)
        run: |
          mvn clean test

